# -*- coding: utf-8 -*-
"""Minimos_Cuadrados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13k6ggnsqD6rvRVay4tNVkLMvrMHuBTNV
"""

import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from google.colab import files

uploaded = files.upload()


import io
dataset = pd.read_csv('Salary_Data.csv')
#df2 = pd.read_csv(io.BytesIO(uploaded['Salary_Data.csv']))
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,1].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 1/3, random_state = 0)
regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)
plt.scatter(X_train, y_train, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color ='blue')
plt.show()